nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
npmScopes:
  deepseek-ai:
    npmRegistryServer: "https://registry.npmjs.org"
npmRegistries:
  "//registry.npmjs.org/":
    npmAuthToken: "${DEEPSEEK_NPM_AUTH_TOKEN}"
